// <auto-generated />
using System;
using BusReservation.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BusReservation.API.Migrations
{
    [DbContext(typeof(BusReservationDbContext))]
    [Migration("20251021045050_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BusReservation.API.Models.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BookingReference")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BookingStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CancellationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumberOfSeats")
                        .HasColumnType("int");

                    b.Property<string>("PassengerEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PassengerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PassengerPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int");

                    b.Property<string>("SeatNumbers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("BookingId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("BusReservation.API.Models.Bus", b =>
                {
                    b.Property<int>("BusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BusId"));

                    b.Property<string>("Amenities")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BusName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BusNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BusType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("int");

                    b.HasKey("BusId");

                    b.ToTable("Buses");

                    b.HasData(
                        new
                        {
                            BusId = 1,
                            Amenities = "WiFi, Charging Point, Water Bottle",
                            BasePrice = 800m,
                            BusName = "National Travels",
                            BusNumber = "KA-01-AB-1234",
                            BusType = "AC Sleeper",
                            IsActive = true,
                            TotalSeats = 40
                        },
                        new
                        {
                            BusId = 2,
                            Amenities = "Water Bottle",
                            BasePrice = 500m,
                            BusName = "Royal Coaches",
                            BusNumber = "KA-02-CD-5678",
                            BusType = "Non-AC Seater",
                            IsActive = true,
                            TotalSeats = 45
                        },
                        new
                        {
                            BusId = 3,
                            Amenities = "WiFi, Water Bottle",
                            BasePrice = 600m,
                            BusName = "Intercity Express",
                            BusNumber = "KA-03-EF-9012",
                            BusType = "AC Seater",
                            IsActive = true,
                            TotalSeats = 50
                        },
                        new
                        {
                            BusId = 4,
                            Amenities = "WiFi, Charging Point, Blanket, Water Bottle",
                            BasePrice = 900m,
                            BusName = "Greenline Travels",
                            BusNumber = "KA-04-GH-3456",
                            BusType = "AC Sleeper",
                            IsActive = true,
                            TotalSeats = 35
                        });
                });

            modelBuilder.Entity("BusReservation.API.Models.BusRoute", b =>
                {
                    b.Property<int>("RouteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RouteId"));

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Distance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<TimeSpan>("EstimatedDuration")
                        .HasColumnType("time");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RouteId");

                    b.ToTable("Routes");

                    b.HasData(
                        new
                        {
                            RouteId = 1,
                            Destination = "Mumbai",
                            Distance = 984m,
                            EstimatedDuration = new TimeSpan(0, 16, 0, 0, 0),
                            Source = "Bangalore"
                        },
                        new
                        {
                            RouteId = 2,
                            Destination = "Jaipur",
                            Distance = 280m,
                            EstimatedDuration = new TimeSpan(0, 5, 0, 0, 0),
                            Source = "Delhi"
                        },
                        new
                        {
                            RouteId = 3,
                            Destination = "Bangalore",
                            Distance = 346m,
                            EstimatedDuration = new TimeSpan(0, 7, 0, 0, 0),
                            Source = "Chennai"
                        },
                        new
                        {
                            RouteId = 4,
                            Destination = "Pune",
                            Distance = 565m,
                            EstimatedDuration = new TimeSpan(0, 10, 0, 0, 0),
                            Source = "Hyderabad"
                        });
                });

            modelBuilder.Entity("BusReservation.API.Models.Schedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleId"));

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("AvailableSeats")
                        .HasColumnType("int");

                    b.Property<int>("BusId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JourneyDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RouteId")
                        .HasColumnType("int");

                    b.HasKey("ScheduleId");

                    b.HasIndex("BusId");

                    b.HasIndex("RouteId");

                    b.ToTable("Schedules");

                    b.HasData(
                        new
                        {
                            ScheduleId = 1,
                            ArrivalTime = new DateTime(2025, 10, 23, 14, 0, 0, 0, DateTimeKind.Local),
                            AvailableSeats = 40,
                            BusId = 1,
                            DepartureTime = new DateTime(2025, 10, 22, 22, 0, 0, 0, DateTimeKind.Local),
                            IsActive = true,
                            JourneyDate = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            Price = 850m,
                            RouteId = 1
                        },
                        new
                        {
                            ScheduleId = 2,
                            ArrivalTime = new DateTime(2025, 10, 22, 13, 0, 0, 0, DateTimeKind.Local),
                            AvailableSeats = 45,
                            BusId = 2,
                            DepartureTime = new DateTime(2025, 10, 22, 8, 0, 0, 0, DateTimeKind.Local),
                            IsActive = true,
                            JourneyDate = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            Price = 550m,
                            RouteId = 2
                        },
                        new
                        {
                            ScheduleId = 3,
                            ArrivalTime = new DateTime(2025, 10, 23, 6, 0, 0, 0, DateTimeKind.Local),
                            AvailableSeats = 50,
                            BusId = 3,
                            DepartureTime = new DateTime(2025, 10, 22, 23, 0, 0, 0, DateTimeKind.Local),
                            IsActive = true,
                            JourneyDate = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            Price = 650m,
                            RouteId = 3
                        },
                        new
                        {
                            ScheduleId = 4,
                            ArrivalTime = new DateTime(2025, 10, 23, 6, 0, 0, 0, DateTimeKind.Local),
                            AvailableSeats = 35,
                            BusId = 4,
                            DepartureTime = new DateTime(2025, 10, 22, 20, 0, 0, 0, DateTimeKind.Local),
                            IsActive = true,
                            JourneyDate = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            Price = 950m,
                            RouteId = 4
                        });
                });

            modelBuilder.Entity("BusReservation.API.Models.Booking", b =>
                {
                    b.HasOne("BusReservation.API.Models.Schedule", "Schedule")
                        .WithMany("Bookings")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("BusReservation.API.Models.Schedule", b =>
                {
                    b.HasOne("BusReservation.API.Models.Bus", "Bus")
                        .WithMany("Schedules")
                        .HasForeignKey("BusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BusReservation.API.Models.BusRoute", "Route")
                        .WithMany("Schedules")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bus");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("BusReservation.API.Models.Bus", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("BusReservation.API.Models.BusRoute", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("BusReservation.API.Models.Schedule", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
